#!/bin/bash
# Lines ending with #/ are marked to be removed from single-file releases as they only pertain to development & testing in a multiple-file environment

minecontrol_Version="Dev" # By Jekotia https://github.com/Jekotia/MineControl
minecontrol_Dir=~/".minecontrol/"
minecontrol_var_Dir=$minecontrol_Dir"var/"
minecontrol_Conf=$minecontrol_Dir"minecontrol.conf"
minecontrol_Conf=~/"Dropbox/GitHub/MineControl/src/minecontrol.conf " #/

# Key checks
if [ ! -d "$minecontrol_Dir" ]; then # Checks if $minecontrol_Dir doesn't exist
	echo "Creating ~/.minecontrol/"
	mkdir $minecontrol_Dir
fi

if [ ! -d "${minecontrol_var_Dir}" ]; then # Checks if $minecontrol_var_Dir doesn't exist
	echo "Creating ~/.minecontrol/var/"
	mkdir -p $minecontrol_var_Dir
fi

if [ ! -f "$minecontrol_Conf" ]; then # Checks if $minecontrol_Conf doesn't exist
	echo "$minecontrol_Conf does not exist. Downloading latest minecontrol.conf..."
	wget -vO $minecontrol_Conf https://raw.github.com/Jekotia/MineControl/master/MineControl-Latest.conf && echo "$minecontrol_Conf successfully downloaded. You should edit this file to suit your setup. Use '$0 config' to open the config file for editing at any time." || echo "Failed to download minecontrol.conf!" # Downloads the latest conf file from GitHub
	exit 0
fi

source $minecontrol_Conf # Includes the conf file

if [ ! -d "$server_Dir" ]; then
	echo "Error: The Minecraft server directory specified for server_Dir ($server_Dir) does not exist."
	_error="true"
fi

if [ ! -f "$server_Dir$server_File" ]; then
	echo "Error: The Minecraft server file specified for server_File ($server_File) does not exist."
	_error="true"
fi

command -v $java_Loc >/dev/null || java_err_1="true"

if [ ! -f "$java_Loc" ]; then
	java_err_2="true"
fi

if [ "$java_err_1" = "true" ] && [ "$java_err_2" = "true" ]; then
	echo "Error: The java binary specified for java_Loc ($java_Loc) does not exist."
	_error="true"
fi

# Tests for logging features
if [ ! -d "$logroll_Dir" ] && [ "$log_roll_Enable" = "true" ]; then
	echo "Creating ~/.minecontrol/${log_roll_Dir}"
	mkdir -p $log_roll_Dir
fi

if [ ! -d "$log_Dir" ] && [ "$log_status_Enable" = "true" ]; then
	mkdir -p $log_status_Dir
fi

# End of tests
if [ "$_error" = "true" ]; then # If any of the tests failed, stop the script.
	exit 0
fi

java_Invocation="${java_Loc} ${java_Args} -Xmx${java_Mem} -jar ${server_Dir}${server_File} nogui" # Fully defined java invocation

# var_Dir=$script_Dir"var/" # To be uncommented in releases

forcesavefile=${var_Dir}"forcesave.sh"
twitteralertsfile=${var_Dir}"twitteralerts.sh"

logroll_Dir=~/"Dropbox/GitHub/MineControl/logs/server/"
statuslog=${log_Dir}"status.log"

script_Dir=~/"Dropbox/GitHub/MineControl/src/" #/
. ${script_Dir}"10-control.sh" #/
. ${script_Dir}"15-utilities.sh" #/
. ${script_Dir}"20-backup.sh" #/
. ${script_Dir}"25-common.sh" #/

mcbin=${script_Dir}"35-server.sh"

interactive(){
	echo "[1] View server status."
	echo "[2] Start the server."
	echo "[3] Stop the server."
	echo "[4] Attach to the servers' screen session."
	echo -n "What would you like to do? "
	read int1
	if [ "$int1" == "1" ]; then
		MC status
	elif [ "$int1" == "2" ]; then
		MC start
	elif [ "$int1" == "3" ]; then
		MC stop
	elif [ "$int1" == "4" ]; then
		MC resume
	fi
}

case $1 in
	status)
		bash $mcbin status
		exit 0
		;;
	start)
		if isrunning; then
			echo "Minecraft server is already running."
			exit 0
		else
			screen -dmS $server_Screen bash $mcbin start
			screen -x $server_Screen
			exit 0
		fi
		;;
	stop)
		bash $mcbin stop
		exit 0
		;;
	resume)
		bash $mcbin resume
		exit 0
		;;
	kill)
		bash $mcbin kill
		exit 0
		;;
	-i)
		interactive
		exit 0
		;;
	config)
		$editor_Text $minecontrol_Conf
		;;
	version)
		echo "This is version $minecontrol_Version of MineControl by Jekotia."
		echo "Source is available at https://github.com/Jekotia/MineControl"
		;;
	*)
		bash $mcbin help
		echo "You can also use the '-i' parameter to run this script in interactive mode."
		echo "You executed this script without any parameters."
		echo -n "Would you like to run it in interactive mode? [y/n] "
		var1="n"
		read var1
		if [ "$var1" == "y" ]; then
			interactive
		fi
esac

exit 0
